---
- name: Check if Apache2 is running
  hosts: localhost
  become: yes

  tasks:
    - name: Get Apache2 status
      command: systemctl is-active apache2
      register: apache2_status
      ignore_errors: yes

    - name: Display Apache2 status
      debug:
        var: apache2_status.stdout
